create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.workspaces (id, slug, name)
values ('00000000-0000-0000-0000-000000000001', 'default', 'Default Workspace')
on conflict (id) do nothing;

create table if not exists public.signal_sources (
  id text primary key,
  workspace_id uuid not null default '00000000-0000-0000-0000-000000000001' references public.workspaces(id) on delete cascade,
  name text not null,
  kind text not null default 'collector',
  status text not null default 'active',
  collect_interval_minutes integer,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, name)
);

create table if not exists public.collection_runs (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null default '00000000-0000-0000-0000-000000000001' references public.workspaces(id) on delete cascade,
  source_id text references public.signal_sources(id) on delete set null,
  source text not null,
  status text not null default 'ok',
  item_count integer not null default 0,
  accepted_count integer not null default 0,
  rejected_count integer not null default 0,
  error text not null default '',
  reason text not null default '',
  started_at timestamptz not null,
  finished_at timestamptz not null,
  metadata jsonb not null default '{}'::jsonb,
  schema_version integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists idx_collection_runs_workspace_finished
  on public.collection_runs (workspace_id, finished_at desc);

create index if not exists idx_collection_runs_source_time
  on public.collection_runs (workspace_id, source, finished_at desc);

create table if not exists public.signals (
  id text primary key,
  workspace_id uuid not null default '00000000-0000-0000-0000-000000000001' references public.workspaces(id) on delete cascade,
  source_id text references public.signal_sources(id) on delete set null,
  source text not null,
  canonical_key text not null,
  title text not null,
  url text not null,
  url_hash text not null,
  metric text not null default '',
  summary text not null default '',
  type text not null default '',
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  collected_at timestamptz not null,
  seen_count integer not null default 1,
  quality_score integer not null default 0 check (quality_score between 0 and 100),
  quality_label text not null default '',
  quality_reasons jsonb not null default '[]'::jsonb,
  tags text[] not null default '{}'::text[],
  area text not null default '',
  language text not null default 'ko',
  raw_payload jsonb not null default '{}'::jsonb,
  schema_version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, source, canonical_key)
);

create index if not exists idx_signals_workspace_last_seen
  on public.signals (workspace_id, last_seen_at desc);

create index if not exists idx_signals_workspace_quality
  on public.signals (workspace_id, quality_score desc, last_seen_at desc);

create index if not exists idx_signals_source_last_seen
  on public.signals (workspace_id, source, last_seen_at desc);

create index if not exists idx_signals_area_last_seen
  on public.signals (workspace_id, area, last_seen_at desc);

create index if not exists idx_signals_title_trgm
  on public.signals using gin (title gin_trgm_ops);

create index if not exists idx_signals_tags_gin
  on public.signals using gin (tags);

create index if not exists idx_signals_raw_payload_gin
  on public.signals using gin (raw_payload jsonb_path_ops);

create table if not exists public.signal_observations (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null default '00000000-0000-0000-0000-000000000001' references public.workspaces(id) on delete cascade,
  signal_id text references public.signals(id) on delete cascade,
  collection_run_id uuid references public.collection_runs(id) on delete set null,
  source text not null,
  title text not null,
  url text not null,
  metric text not null default '',
  observed_at timestamptz not null default now(),
  quality_score integer not null default 0 check (quality_score between 0 and 100),
  payload jsonb not null default '{}'::jsonb
);

create index if not exists idx_signal_observations_workspace_observed
  on public.signal_observations (workspace_id, observed_at desc);

create index if not exists idx_signal_observations_signal_observed
  on public.signal_observations (signal_id, observed_at desc);

create index if not exists idx_signal_observations_observed_brin
  on public.signal_observations using brin (observed_at);

create table if not exists public.trend_snapshots (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null default '00000000-0000-0000-0000-000000000001' references public.workspaces(id) on delete cascade,
  reason text not null default 'manual-rank',
  input_count integer not null default 0,
  candidate_count integer not null default 0,
  avg_score integer not null default 0,
  ranking_version text not null default 'v1',
  metadata jsonb not null default '{}'::jsonb,
  schema_version integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists idx_trend_snapshots_workspace_created
  on public.trend_snapshots (workspace_id, created_at desc);

create index if not exists idx_trend_snapshots_reason_created
  on public.trend_snapshots (workspace_id, reason, created_at desc);

create table if not exists public.trend_snapshot_items (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null default '00000000-0000-0000-0000-000000000001' references public.workspaces(id) on delete cascade,
  snapshot_id uuid not null references public.trend_snapshots(id) on delete cascade,
  rank integer not null,
  keyword text not null,
  keyword_key text not null,
  area text not null default '',
  score integer not null default 0 check (score between 0 and 100),
  mentions integer not null default 0,
  confidence integer not null default 0 check (confidence between 0 and 100),
  sources jsonb not null default '[]'::jsonb,
  sample_titles jsonb not null default '[]'::jsonb,
  candidate jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (snapshot_id, rank)
);

create index if not exists idx_trend_snapshot_items_snapshot_score
  on public.trend_snapshot_items (snapshot_id, score desc);

create index if not exists idx_trend_snapshot_items_workspace_keyword
  on public.trend_snapshot_items (workspace_id, keyword_key, created_at desc);

create index if not exists idx_trend_snapshot_items_candidate_gin
  on public.trend_snapshot_items using gin (candidate jsonb_path_ops);

create table if not exists public.content_plans (
  id text primary key,
  workspace_id uuid not null default '00000000-0000-0000-0000-000000000001' references public.workspaces(id) on delete cascade,
  candidate_id text not null default '',
  keyword text not null,
  keyword_key text not null,
  plan jsonb not null,
  candidate jsonb not null default '{}'::jsonb,
  provider text not null default '',
  status text not null default 'draft',
  schema_version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_content_plans_workspace_updated
  on public.content_plans (workspace_id, updated_at desc);

create index if not exists idx_content_plans_workspace_keyword
  on public.content_plans (workspace_id, keyword_key);

create index if not exists idx_content_plans_plan_gin
  on public.content_plans using gin (plan jsonb_path_ops);

create table if not exists public.content_plan_versions (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null default '00000000-0000-0000-0000-000000000001' references public.workspaces(id) on delete cascade,
  content_plan_id text not null references public.content_plans(id) on delete cascade,
  version integer not null,
  plan jsonb not null,
  provider text not null default '',
  created_at timestamptz not null default now(),
  unique (content_plan_id, version)
);

create table if not exists public.search_verifications (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null default '00000000-0000-0000-0000-000000000001' references public.workspaces(id) on delete cascade,
  query text not null,
  query_key text not null,
  content_type text not null default '',
  provider text not null default '',
  grade text not null default '',
  score_boost integer not null default 0,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create index if not exists idx_search_verifications_workspace_query
  on public.search_verifications (workspace_id, query_key, created_at desc);

create index if not exists idx_search_verifications_expires
  on public.search_verifications (expires_at)
  where expires_at is not null;

create table if not exists public.generated_assets (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null default '00000000-0000-0000-0000-000000000001' references public.workspaces(id) on delete cascade,
  content_plan_id text references public.content_plans(id) on delete set null,
  kind text not null default 'card_image',
  provider text not null default '',
  prompt text not null default '',
  asset_url text not null default '',
  storage_bucket text not null default '',
  storage_path text not null default '',
  status text not null default 'generated',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_generated_assets_plan_created
  on public.generated_assets (content_plan_id, created_at desc);

create table if not exists public.job_runs (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null default '00000000-0000-0000-0000-000000000001' references public.workspaces(id) on delete cascade,
  job_type text not null,
  status text not null default 'running',
  reason text not null default '',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  heartbeat_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  error text not null default ''
);

create index if not exists idx_job_runs_workspace_type_started
  on public.job_runs (workspace_id, job_type, started_at desc);

create index if not exists idx_job_runs_running
  on public.job_runs (workspace_id, job_type, heartbeat_at desc)
  where status = 'running';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_workspaces_updated_at on public.workspaces;
create trigger set_workspaces_updated_at
before update on public.workspaces
for each row execute function public.set_updated_at();

drop trigger if exists set_signal_sources_updated_at on public.signal_sources;
create trigger set_signal_sources_updated_at
before update on public.signal_sources
for each row execute function public.set_updated_at();

drop trigger if exists set_signals_updated_at on public.signals;
create trigger set_signals_updated_at
before update on public.signals
for each row execute function public.set_updated_at();

drop trigger if exists set_content_plans_updated_at on public.content_plans;
create trigger set_content_plans_updated_at
before update on public.content_plans
for each row execute function public.set_updated_at();

alter table public.workspaces enable row level security;
alter table public.signal_sources enable row level security;
alter table public.signals enable row level security;
alter table public.signal_observations enable row level security;
alter table public.collection_runs enable row level security;
alter table public.trend_snapshots enable row level security;
alter table public.trend_snapshot_items enable row level security;
alter table public.content_plans enable row level security;
alter table public.content_plan_versions enable row level security;
alter table public.search_verifications enable row level security;
alter table public.generated_assets enable row level security;
alter table public.job_runs enable row level security;

insert into public.signal_sources (id, name, collect_interval_minutes)
values
  ('google', 'Google Trends', 30),
  ('serp', 'Search SERP', 30),
  ('dcinside', 'DCInside', 30),
  ('fmkorea', 'FMKorea', 30),
  ('theqoo', 'TheQoo', 30),
  ('natepann', 'Nate Pann', 30),
  ('bobaedream', 'BobaeDream', 30),
  ('reddit', 'Reddit', 30),
  ('ruliweb', 'Ruliweb', 30),
  ('inven', 'Inven', 30),
  ('arcalive', 'ArcaLive', 30),
  ('mlbpark', 'MLBPark', 30),
  ('clien', 'Clien', 30)
on conflict (id) do update set
  name = excluded.name,
  collect_interval_minutes = excluded.collect_interval_minutes;
